### ISSUE TITLE
无法获取js，图片，css等资源文件数据

### ISSUE THREAD

**Issue by hongyu2016** [ksky521/devtools-pro#13]
无法获取到所有js，图片，css等资源文件的数据，另外，页面初始化的xhr也无法获取到详情数据，都是空白的。

**Comment by ksky521** [comment]
是有这个问题的，一开始的网络请求是通过performance接口获取的，所以没有数据，后面的都是通过hook xhr/fetch等方式拿到的url，内容除了xhr都没拿到，如果要拿到多做一次请求又觉得得不偿失，综合来说只有网络请求的url已经够用了，所以这块就没深入做

**Comment by hongyu2016** [comment]
这块应该是可以做的吧，钉钉在这块都可以做到图片获取，初始化的xhr请求等等。只是我这边没玩过这个。不知道从何下手。能否指导一二？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月15日(周三) 中午1:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ksky521/devtools-pro] 无法获取js，图片，css等资源文件数据 (#13)




 
是有这个问题的，一开始的网络请求是通过performance接口获取的，所以没有数据，后面的都是通过hook xhr/fetch等方式拿到的url，内容除了xhr都没拿到，如果要拿到多做一次请求又觉得得不偿失，综合来说只有网络请求的url已经够用了，所以这块就没深入做
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ksky521** [comment]
钉钉的什么工具？

**Comment by hongyu2016** [comment]
也是在这个谷歌的devtools上开发的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 下午2:17
收件人: ***@***.***&gt;; 
抄送: "Hong ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ksky521/devtools-pro] 无法获取js，图片，css等资源文件数据 (#13)





 
钉钉的什么工具？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ksky521** [comment]
你说的是钉钉app客户端？还是钉钉出了一个devtools工具？来个地址学习下

**Comment by hongyu2016** [comment]
https://developers.dingtalk.com/document/resourcedownload/h5-micro-application-debugging-tool?pnamespace=app


就是差不多一样的东西，你可以看看。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ksky521/devtools-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:20
***@***.***&gt;;
抄送:&nbsp;"Hong ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ksky521/devtools-pro] 无法获取js，图片，css等资源文件数据 (#13)





 
你说的是钉钉app客户端？还是钉钉出了一个devtools工具？来个地址学习下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ksky521** [comment]
哦，我看了钉钉的微应用devtools，他这个应该是在sdk里面就封装了request和response的hook，跟直接hook原生方法不一样，devtools-pro的方法你可以在https://github.com/ksky521/chobitsu 找到，具体看：https://github.com/ksky521/chobitsu/blob/master/src/domains/Network.ts

**Comment by hongyu2016** [comment]
这样子？或者你这边也试试？看看能否把这个功能加上？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ksky521/devtools-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:24
***@***.***&gt;;
抄送:&nbsp;"Hong ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ksky521/devtools-pro] 无法获取js，图片，css等资源文件数据 (#13)





 
哦，我看了钉钉的微应用devtools，他这个应该是在sdk里面就封装了request和response的hook，跟直接hook原生方法不一样，devtools-pro的方法你可以在https://github.com/ksky521/chobitsu 找到，具体看：https://github.com/ksky521/chobitsu/blob/master/src/domains/Network.ts
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
