### ISSUE TITLE
inspector页面打不开

### ISSUE THREAD

**Issue by jiangxinge** [ksky521/devtools-pro#21]
版本：devtools-pro@0.1.5

环境：
- node: 12.22.8
- os: macOS12.1

表现：
inspector页面打不开，报错信息如下
<img width="621" alt="4c5d8f3acbc4bd41d197d587c5e20827" src="https://user-images.githubusercontent.com/31657341/147226468-4d9d4503-ce15-48a0-869c-0587e2ba9cd6.png">

**Comment by BUPTlhuanyu** [comment]
可以先试试拉去最新代码
```
yarn
yarn build
yarn dev
```
打开调试页面：ip:8081，点击安装证书按钮，手机扫码安装证书之后，打开 charles，代理到charles的8888端口，既可以开始调试
![image](https://user-images.githubusercontent.com/27213108/147319978-6563ae9a-0152-4312-99b6-adef8e2c6606.png)
